### ISSUE TITLE
item.Target中不能用ip来替换域名

### ISSUE THREAD

**Issue by it-man-cn** [URLooker/web#10]
https://github.com/URLooker/web/blob/50de391e3718c09227a3735e1f637d63ee48ba57/cron/fetcher.go#L90
如果web server限制了以server name的方式来访问，check中item.Target以ip来组装成url的方式就不能正常工作

**Comment by 710leo** [comment]
@it-man-cn 这个属于产品的定位不同，不算是代码问题
