### ISSUE TITLE
启动后报错

### ISSUE THREAD

**Issue by fengallan0** [URLooker/web#15]
你好，我启动web组件以后，日志里面一直输出
Unknown column 'ip' in 'field list'
请问什么是什么原因导致的呢？

**Comment by switchchow** [comment]
检查下数据库表吧，有没有将scache.sql导入，或者您是手动执行的sql?

**Comment by 710leo** [comment]
@fengallan0 使用最新的[sql文件](https://github.com/URLooker/web/blob/master/schema.sql)导入就没问题了
