### ISSUE TITLE
strconv.ParseInt: parsing "user": invalid syntax

### ISSUE THREAD

**Issue by leowww24** [URLooker/web#19]
![image](https://user-images.githubusercontent.com/5772601/61164791-036b3a80-a54b-11e9-8b1b-05e2d7817af2.png)

Seems pass parameters error?

**Comment by leoiceo** [comment]
目前发现这个问题只在centos7上出现

**Comment by 710leo** [comment]
前端兼容性问题，换个浏览器即可
