### ISSUE TITLE
配置5个url，只有第一个有图形

### ISSUE THREAD

**Issue by zzlyzq** [URLooker/web#2]
兄弟：

配置5个url，只有第一个有图形。 啥情况来。

**Comment by 710leo** [comment]
@zzlyzq 再详细描述下情况吧，现在说的有些笼统

**Comment by zzlyzq** [comment]
嗯 明天找时间我整理下。

我又重新安装了一次，图形正常了。 不过， 报警会提示email非法，debug中也有信息，稍后我挂上来。
