### ISSUE TITLE
请教一下为什么我的状态图下面的列表不显示是什么问题

### ISSUE THREAD

**Issue by LeonQiuM** [URLooker/web#7]
如下图：添加了四五个都没有

![qq20170410-172240](https://cloud.githubusercontent.com/assets/17693947/24854804/5a70706a-1e12-11e7-8bc9-2b35d4736b2d.png)

**Comment by 710leo** [comment]
@forsaken527  下面列表中有信息需要满足两个要求：
- alarm组件是启动状态且web配置中alarm是打开的 
- 告警被触发
