### ISSUE TITLE
程序崩溃

### ISSUE THREAD

**Issue by luckymrwang** [URLooker/web#8]
在 web/api/item 中 58 行如下代码

```
isSuccess := Q.PushFront(itemStatus)
if !isSuccess {
	log.Println("error:", err)
	*reply = "save item error:" + err.Error()
	return nil
}
```
如果 `!isSuccess` 成立，而 `err` 为 `nil` 时，则 `*reply = "save item error:" + err.Error()` 中的 `err.Error()` 会报错使程序崩溃

**Comment by 710leo** [comment]
@luckymrwang 感谢反馈，问题已[修复 ](https://github.com/URLooker/web/commit/14de7b17ebfd196864484695dc7ca05fe15a6dcf) ：）
