### ISSUE TITLE
urlooker 往falcon+ push数据， 但是在falcon Dashboard看不到曲线图

### ISSUE THREAD

**Issue by leonzhao2020** [URLooker/web#9]
发不了截图，截图已经发到QQ群了。

web/cfg.json 已经修改为transfer地址

>     "falcon":{
>         "enable": true,
>         "addr":"http://127.0.0.1:6060/api/push",
>         "interval": 30
>     },
> 
> 

另外agent tail一直有下面输出，这正常吗？

> 
> 2017/08/09 10:26:13 check.go:37: no found item assigned toagent_77
> 2017/08/09 10:27:13 check.go:37: no found item assigned toagent_77
> 2017/08/09 10:28:13 check.go:37: no found item assigned toagent_77
> 2017/08/09 10:29:13 check.go:37: no found item assigned toagent_77
> 2017/08/09 10:30:13 check.go:37: no found item assigned toagent_77
> 2017/08/09 10:31:13 check.go:37: no found item assigned toagent_77

**Comment by 710leo** [comment]
@ask870 应该是你transfer地址写的不正确，能提供更详细的信息吗？
